# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'HikerJeffSilentStripeTest' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Stripe', '~> 6.2.0'
platform :ios, "9.0"
use_frameworks!
pod 'Alamofire', '~> 3.3'

end
